## 20.02.2023
#### Ćwiczenie 1

In [1]:
import numpy as np

#### Biblioteki numpy, pandas, random.
###### 1. Przygotować wektor wertykalny (A) zawierający 10 argumentów z przedziału 1:20 (array(10,0)).

In [2]:
vectA = np.array([1, 3, 4, 5, 6, 11, 15, 16, 19, 20])

###### 2. Przygotować wektor wertykalny (B) zawierający 10 argumentów z przedziału 0:1 (array(10,0)).

In [3]:
vectB = np.array([2, 4, 5, 6, 8, 8, 8, 8, 9, 10])

###### 3. Wykonać mnożenie dwóch wektorów A i B

In [4]:
AxB = vectA*vectB
print(AxB)

[  2  12  20  30  48  88 120 128 171 200]


###### 4. Następnie wykonać mnożenie skalarne wektora A oraz c = 2.

In [5]:
c = 2
cxA = c * vectA
print(cxA)

[ 2  6  8 10 12 22 30 32 38 40]


###### 5. Stworzyć macierz 4x4 (W), w których argumenty powinny być losowymi liczbami całkowitymi o wartościach z przedziału 1:100.

In [6]:
W = np.random.randint(100, size=(4, 4))
print(W)

[[79 95  2 66]
 [41 13 77 50]
 [54 76 92 74]
 [70 92 91 12]]


###### 6. Wyznaczyć przekątną macierzy

In [7]:
print(np.diagonal(W))

[79 13 92 12]


###### 7. Przeprowadzić transponowanie macierzy 'na piechotę'.

In [8]:
print(f'Tutaj macierz transponowana komendą:')
print(f'{W.transpose()}')
print(
)

print('Tu na piechotę:')
print('[16, 24, 49, 41]')
print('[41, 12, 99, 56]')
print('[56, 23, 80, 65]')
print('[79, 27, 40, 32]')

Tutaj macierz transponowana komendą:
[[79 41 54 70]
 [95 13 76 92]
 [ 2 77 92 91]
 [66 50 74 12]]

Tu na piechotę:
[16, 24, 49, 41]
[41, 12, 99, 56]
[56, 23, 80, 65]
[79, 27, 40, 32]


### Ćwiczenie 2
##### Biblioteki numpy, pandas, random

In [9]:
import random
import pandas as pd

###### 1. Import danych https://www.kaggle.com/datasets/mattop/2022nfl-team-offense

In [20]:
pd.read_csv('nfloffenseweek3.csv')

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    17   Los Angeles Chargers      3             58         1068   
16    18        New York Giants      3             56          995   
17    20          New York Jets      3             52         1110   
18    21          Chicago Bears      3             52          795   
19    22   Tampa Bay Buccaneers      3             51          892   
20    23     New Orleans Saints      3             51         1119   
21    24       Tennessee Titans      3             51          907   
22    25   New England Patriots      3             50         1094   
23    26         Houston Texans      3             49          862   
24    27      Green Bay Packers      3             48         1067   
25    28       Seattle Seahawks      3             47          889   
26    29    San Francisco 49ers      3             47          971   
27    30         Dallas Cowboys      3             46          972   
28    31         Denver Broncos      3             43         1044   
29    32     Indianapolis Colts      3             40          994   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
0               166             6.9               3             1         55   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
6               204             5.5               1             0         70   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
10              182             5.7               5             1         62   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
15              197             5.4               3             1         55   
16              195             5.1               3             1         59   
17              222             5.0               7             4         63   
18              159             5.0               4             0         43   
19              186             4.8               4             3         50   
20              187             6.0               9             4         55   
21              168             5.4               6             3        

In [19]:
dane = pd.read_csv('nfloffenseweek3.csv')

###### 2. Sprawdź, ile razy gracze z Miami Dolphins występują w tym zbiorze danych. Znajdź indeks gracza z "Arizona Cardinals".

In [12]:
df = dane['team']
print(df)

0          Baltimore Ravens
1             Detroit Lions
2             Buffalo Bills
3        Kansas City Chiefs
4       Philadelphia Eagles
5          Cleveland Browns
6      Jacksonville Jaguars
7            Miami Dolphins
8           Atlanta Falcons
9        Cincinnati Bengals
10        Las Vegas Raiders
11    Washington Commanders
12        Arizona Cardinals
13        Carolina Panthers
14         Los Angeles Rams
15     Los Angeles Chargers
16          New York Giants
17            New York Jets
18            Chicago Bears
19     Tampa Bay Buccaneers
20       New Orleans Saints
21         Tennessee Titans
22     New England Patriots
23           Houston Texans
24        Green Bay Packers
25         Seattle Seahawks
26      San Francisco 49ers
27           Dallas Cowboys
28           Denver Broncos
29       Indianapolis Colts
Name: team, dtype: object


In [13]:
'''
teams = ['Baltimore Ravens', 'Detroit Lions', 'Buffalo Bills', 'Kansas City Chiefs',
         'Philadelphia Eagles', 'Cleveland Browns', 'Jacksonville Jaguars', 'Miami Dolphins',
         'Atlanta Falcons', 'Cincinnati Bengals', 'Las Vegas Raiders', 'Washington Commanders',
         'Arizona Cardinals', 'Carolina Panthers', 'Los Angeles Rams', 'Minnesota Vikings',
         'Los Angeles Chargers', 'New York Giants', 'Pittsburgh Steelers', 'New York Jets',
         'Chicago Bears', 'Tampa Bay Buccaneers', 'New Orleans Saints', 'Tennessee Titans',
         'New England Patriots', 'Houston Texans', 'Green Bay Packers', 'Seattle Seahawks',
         'San Francisco 49ers', 'Dallas Cowboys', 'Denver Broncos', 'Indianapolis Colts']

df = pd.DataFrame({'team': teams})

counts = df['team'].value_counts()
liczba = counts['Miami Dolphins']

print(f'Miami Dolphins w powyższej liście występują {liczba} raz(y).')

Ale tak naprawde mozna to zrobic tak:

'''

liczba = dane['team'].value_counts()['Miami Dolphins']
print(f'Miami Dolphins w powyższej liście występują {liczba} raz(y).')

Miami Dolphins w powyższej liście występują 1 raz(y).


###### 3. Zmniejsz rozmiar zestawu danych do 30x28, używając funkcji losowej, aby wybrać dwa wiersze do usunięcia.

In [14]:
a = random.randint(1, 30)
b = random.randint(1, 30)
print(a)
print(b)

28
10


In [26]:
data = dane.drop([a, b], axis=0)

data

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    17   Los Angeles Chargers      3             58         1068   
16    18        New York Giants      3             56          995   
17    20          New York Jets      3             52         1110   
18    21          Chicago Bears      3             52          795   
19    22   Tampa Bay Buccaneers      3             51          892   
20    23     New Orleans Saints      3             51         1119   
21    24       Tennessee Titans      3             51          907   
22    25   New England Patriots      3             50         1094   
23    26         Houston Texans      3             49          862   
24    27      Green Bay Packers      3             48         1067   
25    28       Seattle Seahawks      3             47          889   
26    29    San Francisco 49ers      3             47          971   
27    30         Dallas Cowboys      3             46          972   
29    32     Indianapolis Colts      3             40          994   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
0               166             6.9               3             1         55   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
6               204             5.5               1             0         70   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
15              197             5.4               3             1         55   
16              195             5.1               3             1         59   
17              222             5.0               7             4         63   
18              159             5.0               4             0         43   
19              186             4.8               4             3         50   
20              187             6.0               9             4         55   
21              168             5.4               6             3         50   
22              183             6.0               8             3         57   
23              184             4.7               3             1         52   
24              188             5.7               5  

###### 4. Zamień pierwszą kolumnę z trzecią kolumną, a drugi wiersz z ostatnim.

In [27]:
# Switch the positions of the first and third columns
data = data.iloc[:, [2, 1, 0] + list(range(3, len(data.columns)))]

# Swap the positions of the second and last rows
data = data.iloc[[len(data)-1] + list(range(1, len(data)-1)) + [0], :]

data

games                   team  rank  points_scored  total_yards  \
29      3     Indianapolis Colts    32             40          994   
1       3          Detroit Lions     2             95         1227   
2       3          Buffalo Bills     3             91         1324   
3       3     Kansas City Chiefs     4             88         1122   
4       3    Philadelphia Eagles     5             86         1341   
5       3       Cleveland Browns     6             85         1136   
6       3   Jacksonville Jaguars     7             84         1127   
7       3         Miami Dolphins     8             83         1066   
8       3        Atlanta Falcons     9             80         1063   
9       3     Cincinnati Bengals    10             64         1016   
11      3  Washington Commanders    12             63         1026   
12      3      Arizona Cardinals    13             62         1060   
13      3      Carolina Panthers    14             62          829   
14      3       Los Angeles Rams    15             61          919   
15      3   Los Angeles Chargers    17             58         1068   
16      3        New York Giants    18             56          995   
17      3          New York Jets    20             52         1110   
18      3          Chicago Bears    21             52          795   
19      3   Tampa Bay Buccaneers    22             51          892   
20      3     New Orleans Saints    23             51         1119   
21      3       Tennessee Titans    24             51          907   
22      3   New England Patriots    25             50         1094   
23      3         Houston Texans    26             49          862   
24      3      Green Bay Packers    27             48         1067   
25      3       Seattle Seahawks    28             47          889   
26      3    San Francisco 49ers    29             47          971   
27      3         Dallas Cowboys    30             46          972   
0       3       Baltimore Ravens     1             99         1141   

    offensive_plays  yards_per_play  turnovers_lost  fumbles_lost  1st_downs  \
29              207             4.8               6             2         61   
1               203             6.0               2             0         63   
2               213             6.2               5             3         77   
3               180             6.2               3             2         68   
4               208             6.4               1             0         73   
5               210             5.4               1             0         74   
6               204             5.5               1             0         70   
7               167             6.4               2             0         60   
8               181             5.9               7             4         67   
9               227             4.5               6             2         71   
11              216             4.8               5             2         67   
12              222             4.8               1             0         69   
13              163             5.1               3             2         45   
14              175             5.3               7             2         58   
15              197             5.4               3             1         55   
16              195             5.1               3             1         59   
17              222             5.0               7             4         63   
18              159             5.0               4             0         43   
19              186             4.8               4             3         50   
20              187             6.0               9             4         55   
21              168             5.4               6             3         50   
22              183             6.0               8             3         57   
23              184             4.7               3             1         52   
24              188             5.7               5  


###### 5. Zapisz zestaw danych po transformacji w pliku CSV i XSLX.

In [34]:
data.to_csv('data.csv', index=False)

In [42]:
writer = pd.ExcelWriter('output.xlsx', engine='openpyxl')
data.to_excel(writer, index=False)
writer.save()


###### 6. Sprawdź nazwy kolumn (zapisz je)

In [44]:
listakolumn = (dane.columns)
listakolumn

Index(['rank', 'team', 'games', 'points_scored', 'total_yards',
       'offensive_plays', 'yards_per_play', 'turnovers_lost', 'fumbles_lost',
       '1st_downs', 'passes_completed', 'passes_attempted', 'passing_yards',
       'passing_touchdowns', 'passing_interceptions',
       'net_yards_per_pass_attempt', 'passing_1st_downs', 'rushing_attempts',
       'rushing_yards', 'rushing_touchdowns', 'rushing_yards_per_attempt',
       'rushing_1st_downs', 'penalties', 'penalty_yards', '1st_down_penalties',
       'percentage_scoring_drives', 'percentage_turnover_drives',
       'expected_points'],
      dtype='object')

###### 7. Znajdź 5 pierwszych i 7 ostatnich elementów w serii (zapisz je)

In [49]:

print("First 5 elements:")
print(listakolumn[:5])

print("Last 7 elements:")
print(listakolumn[-7:])

First 5 elements:
Index(['rank', 'team', 'games', 'points_scored', 'total_yards'], dtype='object')
Last 7 elements:
Index(['rushing_1st_downs', 'penalties', 'penalty_yards', '1st_down_penalties',
       'percentage_scoring_drives', 'percentage_turnover_drives',
       'expected_points'],
      dtype='object')


###### 8. Za pomocą funkcji iloc znajdź piąty obiekt w trzeciej kolumnie (zapisz go w nowej zmiennej).

In [52]:
dane.iloc[6, 3]

84

###### 9. Usuń szóstą kolumnę (zapisz ją w nowej zmiennej).

In [70]:
print(new_df)

dane

    offensive_plays
0               166
1               203
2               213
3               180
4               208
5               210
6               204
7               167
8               181
9               227
10              182
11              216
12              222
13              163
14              175
15              197
16              195
17              222
18              159
19              186
20              187
21              168
22              183
23              184
24              188
25              165
26              189
27              184
28              199
29              207


rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    17   Los Angeles Chargers      3             58         1068   
16    18        New York Giants      3             56          995   
17    20          New York Jets      3             52         1110   
18    21          Chicago Bears      3             52          795   
19    22   Tampa Bay Buccaneers      3             51          892   
20    23     New Orleans Saints      3             51         1119   
21    24       Tennessee Titans      3             51          907   
22    25   New England Patriots      3             50         1094   
23    26         Houston Texans      3             49          862   
24    27      Green Bay Packers      3             48         1067   
25    28       Seattle Seahawks      3             47          889   
26    29    San Francisco 49ers      3             47          971   
27    30         Dallas Cowboys      3             46          972   
28    31         Denver Broncos      3             43         1044   
29    32     Indianapolis Colts      3             40          994   

    yards_per_play  turnovers_lost  fumbles_lost  1st_downs  passes_completed  \
0              6.9               3             1         55                56   
1              6.0               2             0         63                66   
2              6.2               5             3         77                94   
3              6.2               3             2         68                74   
4              6.4               1             0         73                66   
5              5.4               1             0         74                61   
6              5.5               1             0         70                77   
7              6.4               2             0         60                72   
8              5.9               7             4         67                50   
9              4.5               6             2         71                80   
10             5.7               5             1         62                74   
11             4.8               5             2         67                82   
12             4.8               1             0         69                92   
13             5.1               3             2         45                42   
14             5.3               7             2         58                74   
15             5.4               3             1         55                84   
16             5.1               3             1         59                59   
17             5.0               7             4         63                92   
18             5.0               4             0         43                23   
19             4.8               4             3         50                67   
20             6.0               9             4         55                73   
21             5.4               6             3   

###### 10. Połącz (concat) kolumnę z punktu 9 z resztą serii i zapisz ją w nowej zmiennej.

In [73]:
dane = pd.concat([dane, new_df], axis=1)
dane

rank                   team  games  points_scored  total_yards  \
0      1       Baltimore Ravens      3             99         1141   
1      2          Detroit Lions      3             95         1227   
2      3          Buffalo Bills      3             91         1324   
3      4     Kansas City Chiefs      3             88         1122   
4      5    Philadelphia Eagles      3             86         1341   
5      6       Cleveland Browns      3             85         1136   
6      7   Jacksonville Jaguars      3             84         1127   
7      8         Miami Dolphins      3             83         1066   
8      9        Atlanta Falcons      3             80         1063   
9     10     Cincinnati Bengals      3             64         1016   
10    11      Las Vegas Raiders      3             64         1040   
11    12  Washington Commanders      3             63         1026   
12    13      Arizona Cardinals      3             62         1060   
13    14      Carolina Panthers      3             62          829   
14    15       Los Angeles Rams      3             61          919   
15    17   Los Angeles Chargers      3             58         1068   
16    18        New York Giants      3             56          995   
17    20          New York Jets      3             52         1110   
18    21          Chicago Bears      3             52          795   
19    22   Tampa Bay Buccaneers      3             51          892   
20    23     New Orleans Saints      3             51         1119   
21    24       Tennessee Titans      3             51          907   
22    25   New England Patriots      3             50         1094   
23    26         Houston Texans      3             49          862   
24    27      Green Bay Packers      3             48         1067   
25    28       Seattle Seahawks      3             47          889   
26    29    San Francisco 49ers      3             47          971   
27    30         Dallas Cowboys      3             46          972   
28    31         Denver Broncos      3             43         1044   
29    32     Indianapolis Colts      3             40          994   

    yards_per_play  turnovers_lost  fumbles_lost  1st_downs  passes_completed  \
0              6.9               3             1         55                56   
1              6.0               2             0         63                66   
2              6.2               5             3         77                94   
3              6.2               3             2         68                74   
4              6.4               1             0         73                66   
5              5.4               1             0         74                61   
6              5.5               1             0         70                77   
7              6.4               2             0         60                72   
8              5.9               7             4         67                50   
9              4.5               6             2         71                80   
10             5.7               5             1         62                74   
11             4.8               5             2         67                82   
12             4.8               1             0         69                92   
13             5.1               3             2         45                42   
14             5.3               7             2         58                74   
15             5.4               3             1         55                84   
16             5.1               3             1         59                59   
17             5.0               7             4         63                92   
18             5.0               4             0         43                23   
19             4.8               4             3         50                67   
20             6.0               9             4         55                73   
21             5.4               6             3   